{
 "title": "Trace metrics",
 "description": "Metrics derived from traces",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "customer" }
  ]
 },
 "panels": [
  {
   "title": "Network latency, client",
   "type": "graph",
   "description": "Network latency between services",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_latency_seconds_bucket{client=\"$service\"}\n"
    }
   ]
  },
  {
   "title": "Network latency, server",
   "type": "graph",
   "description": "Network latencies between services",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "network_latency_seconds_bucket{server=\"$service\"}"
    }
   ]
  },
  {
   "title": "Service parents",
   "type": "graph",
   "description": "Service's direct upstream connections/parents",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_parents_total{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Service dependencies",
   "type": "graph",
   "description": "Service dependencies",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_dependencies_total{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Service depth",
   "type": "graph",
   "description": " number of service hops from a service to the root service",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_depth_total{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Service height",
   "type": "graph",
   "description": "Number of service hops from a service to the leaf service",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_height_total{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "Trace height",
   "type": "graph",
   "description": "trace tree height. Maximum number of spans from root to leaf",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "trace_height_total" }
   ]
  }
 ]
}