// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoc-gen-swagger/options/annotations.proto

package grpc.gateway.protoc_gen_swagger.options;

public final class Annotations {
  private Annotations() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(grpc.gateway.protoc_gen_swagger.options.Annotations.openapiv2Swagger);
    registry.add(grpc.gateway.protoc_gen_swagger.options.Annotations.openapiv2Operation);
    registry.add(grpc.gateway.protoc_gen_swagger.options.Annotations.openapiv2Schema);
    registry.add(grpc.gateway.protoc_gen_swagger.options.Annotations.openapiv2Tag);
    registry.add(grpc.gateway.protoc_gen_swagger.options.Annotations.openapiv2Field);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int OPENAPIV2_SWAGGER_FIELD_NUMBER = 1042;
  /**
   * <pre>
   * ID assigned by protobuf-global-extension-registry&#64;google.com for grpc-gateway project.
   * All IDs are the same, as assigned. It is okay that they are the same, as they extend
   * different descriptor messages.
   * </pre>
   *
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      grpc.gateway.protoc_gen_swagger.options.Openapiv2.Swagger> openapiv2Swagger = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.Swagger.class,
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.Swagger.getDefaultInstance());
  public static final int OPENAPIV2_OPERATION_FIELD_NUMBER = 1042;
  /**
   * <pre>
   * ID assigned by protobuf-global-extension-registry&#64;google.com for grpc-gateway project.
   * All IDs are the same, as assigned. It is okay that they are the same, as they extend
   * different descriptor messages.
   * </pre>
   *
   * <code>extend .google.protobuf.MethodOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MethodOptions,
      grpc.gateway.protoc_gen_swagger.options.Openapiv2.Operation> openapiv2Operation = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.Operation.class,
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.Operation.getDefaultInstance());
  public static final int OPENAPIV2_SCHEMA_FIELD_NUMBER = 1042;
  /**
   * <pre>
   * ID assigned by protobuf-global-extension-registry&#64;google.com for grpc-gateway project.
   * All IDs are the same, as assigned. It is okay that they are the same, as they extend
   * different descriptor messages.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      grpc.gateway.protoc_gen_swagger.options.Openapiv2.Schema> openapiv2Schema = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.Schema.class,
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.Schema.getDefaultInstance());
  public static final int OPENAPIV2_TAG_FIELD_NUMBER = 1042;
  /**
   * <pre>
   * ID assigned by protobuf-global-extension-registry&#64;google.com for grpc-gateway project.
   * All IDs are the same, as assigned. It is okay that they are the same, as they extend
   * different descriptor messages.
   * </pre>
   *
   * <code>extend .google.protobuf.ServiceOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.ServiceOptions,
      grpc.gateway.protoc_gen_swagger.options.Openapiv2.Tag> openapiv2Tag = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.Tag.class,
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.Tag.getDefaultInstance());
  public static final int OPENAPIV2_FIELD_FIELD_NUMBER = 1042;
  /**
   * <pre>
   * ID assigned by protobuf-global-extension-registry&#64;google.com for grpc-gateway project.
   * All IDs are the same, as assigned. It is okay that they are the same, as they extend
   * different descriptor messages.
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      grpc.gateway.protoc_gen_swagger.options.Openapiv2.JSONSchema> openapiv2Field = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.JSONSchema.class,
        grpc.gateway.protoc_gen_swagger.options.Openapiv2.JSONSchema.getDefaultInstance());

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n,protoc-gen-swagger/options/annotations" +
      ".proto\022\'grpc.gateway.protoc_gen_swagger." +
      "options\032 google/protobuf/descriptor.prot" +
      "o\032*protoc-gen-swagger/options/openapiv2." +
      "proto:j\n\021openapiv2_swagger\022\034.google.prot" +
      "obuf.FileOptions\030\222\010 \001(\01320.grpc.gateway.p" +
      "rotoc_gen_swagger.options.Swagger:p\n\023ope" +
      "napiv2_operation\022\036.google.protobuf.Metho" +
      "dOptions\030\222\010 \001(\01322.grpc.gateway.protoc_ge" +
      "n_swagger.options.Operation:k\n\020openapiv2" +
      "_schema\022\037.google.protobuf.MessageOptions" +
      "\030\222\010 \001(\0132/.grpc.gateway.protoc_gen_swagge" +
      "r.options.Schema:e\n\ropenapiv2_tag\022\037.goog" +
      "le.protobuf.ServiceOptions\030\222\010 \001(\0132,.grpc" +
      ".gateway.protoc_gen_swagger.options.Tag:" +
      "l\n\017openapiv2_field\022\035.google.protobuf.Fie" +
      "ldOptions\030\222\010 \001(\01323.grpc.gateway.protoc_g" +
      "en_swagger.options.JSONSchemaBCZAgithub." +
      "com/grpc-ecosystem/grpc-gateway/protoc-g" +
      "en-swagger/optionsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          grpc.gateway.protoc_gen_swagger.options.Openapiv2.getDescriptor(),
        });
    openapiv2Swagger.internalInit(descriptor.getExtensions().get(0));
    openapiv2Operation.internalInit(descriptor.getExtensions().get(1));
    openapiv2Schema.internalInit(descriptor.getExtensions().get(2));
    openapiv2Tag.internalInit(descriptor.getExtensions().get(3));
    openapiv2Field.internalInit(descriptor.getExtensions().get(4));
    com.google.protobuf.DescriptorProtos.getDescriptor();
    grpc.gateway.protoc_gen_swagger.options.Openapiv2.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
