{
 "title": "Trace quality",
 "description": "Measures trace instrumentation quality",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "query": "frontend" }
  ]
 },
 "panels": [
  {
   "title": "Has server spans",
   "type": "graph",
   "description": "The service emitted spans with tag span.kind=server ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trace_quality_server_tag_total{pass=\"true\",service=\"$service\",} / ignoring (pass,fail) sum without(pass, fail) (trace_quality_server_tag_total)\n",
     "legendFormat": "pass rate"
    },
    {
     "expr": "trace_quality_server_tag_total{pass=\"true\",service=\"$service\",}\n",
     "legendFormat": "pass total"
    },
    {
     "expr": "trace_quality_server_tag_total{pass=\"false\",service=\"$service\",}\n",
     "legendFormat": "fail total"
    },
    {
     "expr": "trace_quality_server_tag_total{pass=\"false\",service=\"$service\",} / ignoring (pass,fail) sum without(pass, fail) (trace_quality_server_tag_total)\n",
     "legendFormat": "fail rate"
    }
   ]
  },
  {
   "title": "Has client spans",
   "type": "graph",
   "description": "The service emitted spans with tag span.kind=client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trace_quality_client_tag_total{pass=\"true\",service=\"$service\",} / ignoring (pass,fail) sum without(pass, fail) (trace_quality_client_tag_total)\n",
     "legendFormat": "pass rate"
    },
    {
     "expr": "trace_quality_client_tag_total{pass=\"true\",service=\"$service\",}\n",
     "legendFormat": "pass total"
    },
    {
     "expr": "trace_quality_client_tag_total{pass=\"false\",service=\"$service\",}\n",
     "legendFormat": "fail total"
    },
    {
     "expr": "trace_quality_client_tag_total{pass=\"false\",service=\"$service\",} / ignoring (pass,fail) sum without(pass, fail) (trace_quality_client_tag_total)\n",
     "legendFormat": "fail rate"
    }
   ]
  },
  {
   "title": "Unique span ID",
   "type": "graph",
   "description": "The service emitted spans with unique span IDs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trace_quality_unique_span_id_total{pass=\"true\",service=\"$service\",} / ignoring (pass,fail) sum without(pass, fail) (trace_quality_unique_span_id_total)\n",
     "legendFormat": "pass rate"
    },
    {
     "expr": "trace_quality_unique_span_id_total{pass=\"true\",service=\"$service\",}",
     "legendFormat": "pass total"
    },
    {
     "expr": "trace_quality_unique_span_id_total{pass=\"false\",service=\"$service\",}",
     "legendFormat": "fail total"
    },
    {
     "expr": "trace_quality_unique_span_id_total{pass=\"false\",service=\"$service\",} / ignoring (pass,fail) sum without(pass, fail) (trace_quality_unique_span_id_total)\n",
     "legendFormat": "fail rate"
    }
   ]
  },
  {
   "title": "Minimum Jaeger client version",
   "type": "graph",
   "description": "The service emitted spans with acceptable Jaeger client version",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "trace_quality_minimum_client_version_total{pass=\"true\",service=\"$service\",} / ignoring (pass,fail) sum without(pass, fail) (trace_quality_minimum_client_version_total)\n",
     "legendFormat": "pass rate"
    },
    {
     "expr": "trace_quality_minimum_client_version_total{pass=\"true\",service=\"$service\",}",
     "legendFormat": "pass total"
    },
    {
     "expr": "trace_quality_minimum_client_version_total{pass=\"false\",service=\"$service\",}",
     "legendFormat": "fail total"
    },
    {
     "expr": "trace_quality_minimum_client_version_total{pass=\"false\",service=\"$service\",} / ignoring (pass,fail) sum without(pass, fail) (trace_quality_minimum_client_version_total)\n",
     "legendFormat": "fail rate"
    }
   ]
  }
 ]
}